apiVersion: batch/v1
kind: Job
metadata:
  name: populate-content
spec:
  template:
    spec:
      containers:
      - name: content-populator
        image: busybox
        command: ['sh', '-c', 'echo "<h1>Hello from NFS!</h1>" > /mnt/index.html']
        volumeMounts:
        - name: web-content
          mountPath: /mnt
      restartPolicy: Never
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc